<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model [
  <!ELEMENT model (query_text, model_path, output_type, parameters?, orders?, columns?)>
  <!ATTLIST model code CDATA "">
  <!ATTLIST model description CDATA "">
  <!ELEMENT query_text (#PCDATA)>
  <!ELEMENT output_type (#PCDATA)>
  <!ELEMENT model_path (#PCDATA)>
  <!ELEMENT parameters (parameter*)>
  <!ELEMENT parameter (expression, param_type, param_sub_type, widget?, str_options?, query_options?)>
  <!ATTLIST parameter code CDATA "">
  <!ATTLIST parameter description CDATA "">
  <!ATTLIST parameter mandatory (true|false) #REQUIRED>
  <!ELEMENT widget (#PCDATA)>
  <!ELEMENT str_options (#PCDATA)>
  <!ELEMENT query_options (#PCDATA)>
  <!ELEMENT param_sub_type (#PCDATA)>  <!ELEMENT param_type (#PCDATA)>  <!ELEMENT expression (#PCDATA)>  <!ELEMENT orders (order*)>
  <!ATTLIST order description CDATA "">
  <!ATTLIST order fields CDATA "">
  <!ELEMENT columns (column*)>
  <!ATTLIST order title CDATA "">
  <!ATTLIST order width CDATA "">
]>

<model code="STR0003" description="List of All Function by Schema">
    <parameters>
        <parameter code="p_schema" description="Schema" mandatory="false">
            <expression><![CDATA[AND n.nspname = ?]]></expression>
            <param_type><![CDATA[Text]]></param_type>
            <param_sub_type><![CDATA[Single]]></param_sub_type>
        </parameter>
    </parameters>
    <orders>
        <order description="Shema + Name" fields="n.nspname, p.proname"/>
        <order description="Schema + Return Type" fields="n.nspname, t.typname"/>
    </orders>
    <columns/>
    <query_text><![CDATA[SELECT  
    quote_ident(n.nspname) as schema_name,
    quote_ident(p.proname) as function_name,
    pg_catalog.pg_get_function_identity_arguments(p.oid) as arguments, 
    t.typname as return_type
FROM   pg_catalog.pg_proc p
       JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace 
       JOIN pg_catalog.pg_type t ON p.prorettype = t.oid
WHERE  TRUE [!p_schema!]]]></query_text>
    <output_type><![CDATA[Html]]></output_type>
    <model_path><![CDATA[]]></model_path>
</model>