<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model [
  <!ELEMENT model (query_text, model_path, output_type, parameters?, orders?, columns?)>
  <!ATTLIST model code CDATA "">
  <!ATTLIST model description CDATA "">
  <!ELEMENT query_text (#PCDATA)>
  <!ELEMENT output_type (#PCDATA)>
  <!ELEMENT model_path (#PCDATA)>
  <!ELEMENT parameters (parameter*)>
  <!ELEMENT parameter (expression, param_type, param_sub_type, widget?, str_options?, query_options?)>
  <!ATTLIST parameter code CDATA "">
  <!ATTLIST parameter description CDATA "">
  <!ATTLIST parameter mandatory (true|false) #REQUIRED>
  <!ELEMENT widget (#PCDATA)>
  <!ELEMENT str_options (#PCDATA)>
  <!ELEMENT query_options (#PCDATA)>
  <!ELEMENT param_sub_type (#PCDATA)>  <!ELEMENT param_type (#PCDATA)>  <!ELEMENT expression (#PCDATA)>  <!ELEMENT orders (order*)>
  <!ATTLIST order description CDATA "">
  <!ATTLIST order fields CDATA "">
  <!ELEMENT columns (column*)>
  <!ATTLIST order title CDATA "">
  <!ATTLIST order width CDATA "">
]>

<model code="INDX0001" description="Index Sizes">
    <parameters/>
    <orders/>
    <columns>
        <column title="Schema" fields="100"/>
        <column title="Index" fields="100"/>
        <column title="Owner" fields="100"/>
        <column title="File Node" fields="100"/>
        <column title="Type" fields="100"/>
        <column title="Total Size" fields="100"/>
        <column title="Total Size (Bytes)" fields="100"/>
    </columns>
    <query_text><![CDATA[SELECT 
    n.nspname as schema,
    c.relname as index,
    a.rolname as owner,
    c.relfilenode as filename,
    CASE 
        WHEN indisprimary THEN 'pkey'
        WHEN indisunique THEN 'uidx' 
        ELSE'idx'
	END as type,
    pg_size_pretty(pg_total_relation_size(n.nspname|| '.' || c.relname)) as total_size,
    pg_total_relation_size(n.nspname|| '.' || c.relname) as total_size_bytes
FROM 
    pg_index i
    JOIN pg_class c ON (c.oid = i.indexrelid)
    JOIN pg_namespace n ON (n.oid = c.relnamespace)
    JOIN pg_authid a ON ( a.oid = c.relowner )
WHERE relname NOT LIKE 'pg_%' AND
    relname NOT LIKE 'information%' AND
    relname NOT LIKE 'sql_%' AND
    relkind IN ('i')    
ORDER BY 7 DESC, 1, 2]]></query_text>
    <output_type><![CDATA[Text With Separators]]></output_type>
    <model_path><![CDATA[Info - Statistics/Indexes]]></model_path>
</model>