<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model [
  <!ELEMENT model (query_text, model_path, output_type, parameters?, orders?, columns?)>
  <!ATTLIST model code CDATA "">
  <!ATTLIST model description CDATA "">
  <!ELEMENT query_text (#PCDATA)>
  <!ELEMENT output_type (#PCDATA)>
  <!ELEMENT model_path (#PCDATA)>
  <!ELEMENT parameters (parameter*)>
  <!ELEMENT parameter (expression, param_type, param_sub_type, widget?, str_options?, query_options?)>
  <!ATTLIST parameter code CDATA "">
  <!ATTLIST parameter description CDATA "">
  <!ATTLIST parameter mandatory (true|false) #REQUIRED>
  <!ELEMENT widget (#PCDATA)>
  <!ELEMENT str_options (#PCDATA)>
  <!ELEMENT query_options (#PCDATA)>
  <!ELEMENT param_sub_type (#PCDATA)>  <!ELEMENT param_type (#PCDATA)>  <!ELEMENT expression (#PCDATA)>  <!ELEMENT orders (order*)>
  <!ATTLIST order description CDATA "">
  <!ATTLIST order fields CDATA "">
  <!ELEMENT columns (column*)>
  <!ATTLIST order title CDATA "">
  <!ATTLIST order width CDATA "">
]>

<model code="ESTR-0001" description="List of Tables">
    <parameters>
        <parameter code="p_schema" description="Schema" mandatory="false">
            <expression><![CDATA[AND schemaname IN ?]]></expression>
            <param_type><![CDATA[Text]]></param_type>
            <param_sub_type><![CDATA[List]]></param_sub_type>
        </parameter>
    </parameters>
    <orders>
        <order description="Schema + Table" fields="1,2"/>
    </orders>
    <columns/>
    <query_text><![CDATA[SELECT
    schemaname, 
    tablename, 
    tableowner, 
    tablespace,
    CASE hasindexes
        WHEN true THEN 'Yes'
        ELSE 'No'
    END AS hasindexes,   
    CASE hasrules
        WHEN true THEN 'Yes'
        ELSE 'No'
    END AS hasrules, 
    CASE hastriggers
        WHEN true THEN 'Yes'
        ELSE 'No'
    END AS hastriggers,
    CASE rowsecurity
        WHEN true THEN 'Yes'
        ELSE 'No'
    END AS rowsecurity
FROM
    pg_catalog.pg_tables
WHERE
    schemaname != 'pg_catalog'
    AND schemaname != 'information_schema'
    [!p_schema!]]]></query_text>
    <output_type><![CDATA[Html]]></output_type>
    <model_path><![CDATA[/Structure/List of Tables]]></model_path>
</model>