<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model [
  <!ELEMENT model (query_text, model_path, output_type, parameters?, orders?, columns?)>
  <!ATTLIST model code CDATA "">
  <!ATTLIST model description CDATA "">
  <!ELEMENT query_text (#PCDATA)>
  <!ELEMENT output_type (#PCDATA)>
  <!ELEMENT model_path (#PCDATA)>
  <!ELEMENT parameters (parameter*)>
  <!ELEMENT parameter (expression, param_type, param_sub_type, widget?, str_options?, query_options?)>
  <!ATTLIST parameter code CDATA "">
  <!ATTLIST parameter description CDATA "">
  <!ATTLIST parameter mandatory (true|false) #REQUIRED>
  <!ELEMENT widget (#PCDATA)>
  <!ELEMENT str_options (#PCDATA)>
  <!ELEMENT query_options (#PCDATA)>
  <!ELEMENT param_sub_type (#PCDATA)>  <!ELEMENT param_type (#PCDATA)>  <!ELEMENT expression (#PCDATA)>  <!ELEMENT orders (order*)>
  <!ATTLIST order description CDATA "">
  <!ATTLIST order fields CDATA "">
  <!ELEMENT columns (column*)>
  <!ATTLIST order title CDATA "">
  <!ATTLIST order width CDATA "">
]>

<model code="STR-0007" description="List of views ">
    <parameters>
        <parameter code="p_schema" description="Schema (List)" mandatory="false">
            <expression><![CDATA[AND schemaname IN ?]]></expression>
            <param_type><![CDATA[Text]]></param_type>
            <param_sub_type><![CDATA[List]]></param_sub_type>
        </parameter>
        <parameter code="p_name" description="View Name" mandatory="false">
            <expression><![CDATA[AND viewname ilike ?]]></expression>
            <param_type><![CDATA[Text]]></param_type>
            <param_sub_type><![CDATA[Single]]></param_sub_type>
        </parameter>
    </parameters>
    <orders>
        <order description="Schema + Name" fields="schemaname, viewname"/>
    </orders>
    <columns/>
    <query_text><![CDATA[SELECT 
    schemaname,  
    viewname, 
    viewowner, 
    definition
FROM pg_catalog.pg_views
WHERE schemaname NOT IN ('pg_catalog', 'information_schema')
      [!p_schema!]
      [!p_name!]]]></query_text>
    <output_type><![CDATA[Text With Separators]]></output_type>
    <model_path><![CDATA[]]></model_path>
</model>