<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model [
  <!ELEMENT model (query_text, model_path, output_type, parameters?, orders?, columns?)>
  <!ATTLIST model code CDATA "">
  <!ATTLIST model description CDATA "">
  <!ELEMENT query_text (#PCDATA)>
  <!ELEMENT output_type (#PCDATA)>
  <!ELEMENT database_request (#PCDATA)>
  <!ELEMENT model_path (#PCDATA)>
  <!ELEMENT parameters (parameter*)>
  <!ELEMENT parameter (expression, param_type, param_sub_type, widget?, str_options?, query_options?)>
  <!ATTLIST parameter code CDATA "">
  <!ATTLIST parameter description CDATA "">
  <!ATTLIST parameter mandatory (true|false) #REQUIRED>
  <!ELEMENT widget (#PCDATA)>
  <!ELEMENT str_options (#PCDATA)>
  <!ELEMENT query_options (#PCDATA)>
  <!ELEMENT param_sub_type (#PCDATA)>  <!ELEMENT param_type (#PCDATA)>  <!ELEMENT expression (#PCDATA)>  <!ELEMENT orders (order*)>
  <!ATTLIST order description CDATA "">
  <!ATTLIST order fields CDATA "">
  <!ELEMENT columns (column*)>
  <!ATTLIST order title CDATA "">
  <!ATTLIST order width CDATA "">
]>

<model code="DLL_ENA_TRIGGERS" description="Enable Trigger">
    <parameters>
        <parameter code="p_schema" description="Schema" mandatory="true">
            <expression><![CDATA[AND n.nspname = ?]]></expression>
            <param_type><![CDATA[Text]]></param_type>
            <param_sub_type><![CDATA[Single]]></param_sub_type>
        </parameter>
        <parameter code="p_table" description="Table Name " mandatory="true">
            <expression><![CDATA[AND tbl.relname = ?]]></expression>
            <param_type><![CDATA[Text]]></param_type>
            <param_sub_type><![CDATA[Single]]></param_sub_type>
        </parameter>
        <parameter code="p_trigger" description="Trigger Name" mandatory="true">
            <expression><![CDATA[AND trg.tgname = ?]]></expression>
            <param_type><![CDATA[Text]]></param_type>
            <param_sub_type><![CDATA[Single]]></param_sub_type>
        </parameter>
    </parameters>
    <orders/>
    <columns/>
    <query_text><![CDATA[SELECT 
    'ALTER TABLE ' || n.nspname || '.' || tbl.relname || ' ENABLE TRIGGER ' || trg.tgname || E';\n' AS disable_trigger
FROM 
    pg_trigger trg
    INNER JOIN pg_class tbl ON trg.tgrelid = tbl.oid
    INNER JOIN pg_namespace n ON tbl.relnamespace = n.oid
WHERE        
    tbl.relname !~ '^pg_'
    [!p_schema!]
    [!p_table!]
    [!p_trigger!]
    AND tgisinternal = FALSE]]></query_text>
    <database_request><![CDATA[yes]]></database_request>
    <output_type><![CDATA[Editor]]></output_type>
    <model_path><![CDATA[/triggers]]></model_path>
</model>